#!/bin/bash

chosen=$(printf "Power Off\nRestart\nLock") | rofi dmenu -i -theme-str '@import "/usr/share/rofi/themes/solarized_alternate.rasi"')

case "$chosen" in
    "Power Off") poweroff ;;
    "Restart") reboot ;;
    "Lock") slock;;
    *) exit 1 ;;
esac